require 'macros'

module SpiderMonkey
  JS_TRUE = 1
  JS_FALSE = 0
  JSVAL_VOID = INT_TO_JSVAL(0 - JSVAL_INT_POW2(30))
  JSVAL_NULL = OBJECT_TO_JSVAL(0)
  JSVAL_ZERO = INT_TO_JSVAL(0)
  JSVAL_ONE =  INT_TO_JSVAL(1)
  JSVAL_FALSE = BOOLEAN_TO_JSVAL(JS_FALSE)
  JSVAL_TRUE = BOOLEAN_TO_JSVAL(JS_TRUE)
end
